/*******************************************************************************

  File Name   : can_defines.h
  Date        : 14.08.2001
  Version     : 1.0
  Desciption  : Vector definitions

*******************************************************************************/


// -----------------------------------------------------------------------------
// General data types
// -----------------------------------------------------------------------------
typedef unsigned char    canuint8;
typedef signed   char    cansint8;
typedef unsigned short   canuint16;
typedef signed   short   cansint16;
typedef unsigned long    canuint32;
typedef signed   long    cansint32;
typedef unsigned char    canbittype;
// -----------------------------------------------------------------------------
